### PR TITLE
feat: Import styles

### PR DESCRIPTION
**Pull request by ajitpsakri**
Pages added 
1. Card Management
image
2. Wishlist
image
3. Product page(2)
image
image
4. Home page
image
5. auth pages 
image
image
image

[Link to sandbox](https://codesandbox.io/s/github/ajitpsakri/Arch-ecommerce/tree/import-styles)

### CODE REVIEW

**Review by mohammed-sas — CHANGES_REQUESTED** [review]
kindly add screemshots for each screens

**Comment by ajitpsakri** [comment]
> kindly add screemshots for each screens

@mohammed-sas Changes that you asked for are made.

**Review by mohammed-sas — APPROVED** [review]
all the screens look neat and clean
pr is good to merge

**Review by GauravDe-git — APPROVED** [review]
- Screens are looking good
- Clean, well-formatted code

Good to merge

**Pull request merged**
